name: XAI_2
dependencies:
  - python=3.7
  - pytorch==1.4.0
  - pip
  - pip:
    - attrs
    - pyyaml
    - torchvision==0.5.0
    - opencv-python==4.1.2.30
    - beautifulsoup4==4.8.1
    - tqdm==4.35.0
    - pandas==0.24.2
    - scikit-learn==0.20.2
    - scipy==1.3.0 
    - scikit-image==0.15.0
